const ActionTypes = {
  EDIT_ABOUT: "EDIT_ABOUT",
  EDIT_CONTACT: "EDIT_CONTACT",
  EDIT_TECH: "EDIT_TECH",
  EDIT_EDUCATION: "EDIT_EDUCATION",
  EDIT_CERTIFICATE: "EDIT_CERTIFICATE",
  EDIT_EVENT: "EDIT_EVENT",
  EDIT_PROJECT: "EDIT_PROJECT",
};

export default ActionTypes;
